language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - phpenv rehash
    - composer install --dev

script:
        vendor/bin/phpcs --standard=PSR2 --report=full src
        vendor/bin/phpunit

